const PORT = process.env.PORT;
const MONGODB_URI = process.env.MONGODB_URI;
const DB_NAME = process.env.DB_NAME;
const CORS_ORIGIN = process.env.CORS_ORIGIN;
const BCRYPT_SALT = Number(process.env.BCRYPT_SALT);
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const ACCESS_TOKEN_EXPIRY = process.env.ACCESS_TOKEN_EXPIRY;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
const REFRESH_TOKEN_EXPIRY = process.env.REFRESH_TOKEN_EXPIRY;
const HTTP_ONLY_COOKIE = process.env.HTTP_ONLY_COOKIE;
const SECURE_COOKIE = process.env.SECURE_COOKIE;
const SAME_SITE = process.env.SAME_SITE;
const COOKIE_DOMAIN = process.env.COOKIE_DOMAIN;

export {
  PORT,
  MONGODB_URI,
  DB_NAME,
  CORS_ORIGIN,
  BCRYPT_SALT,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,
  HTTP_ONLY_COOKIE,
  SECURE_COOKIE,
  SAME_SITE,
  COOKIE_DOMAIN,
};
